export const jobs = [
  // {
  //   id: 0,
  //   header: 'Franchisee Development Manager',
  //   subHeader: 'Retail Sales',
  //   type: 'Full Time',
  //   location: 'Muzaffarpur, Patna, Ranchi',
  //   jobPosted: '7 May 2021',
  //   shortDescription: [
  //     'As a Franchisee Development Manager, you will be responsible for the sales process from initial solicitation through contract completion. Includes identifying and sourcing prospective new franchisees, pipeline maintenance and adherence to sales processes. Must passionately represent the brand(s) and be able to ethically coach prospects through the discovery process, financing resolution and market development. .',
  //   ],
  //   keyResponsibilities: [
  //     '1. Develop new business via outbound calling and mass communication such as email and social media to introduce the Authority Brand Opportunity and identify appropriate buyers within the target market.',
  //     '2. Follow up on leads and conduct research to identify potential Prospects.',
  //     '3. Makes initial qualifying calls to all in-bound leads as assigned.',
  //     '4. Identifies, creates urgency and builds rapport with Decision Makers.',
  //     '5. Conduct a needs analysis and determine prospects pain points.',
  //     '6. Coordinates the effective warm hand-off of the qualified prospect to the assigned FDEs.',
  //     '7. Site Visit to finalize the MOU discussion and further for Site Installation till it&#39;s inauguration.',
  //     '8. Work with the FDEs to develop and grow the sales pipeline to consistently meet quarterly sales goals.',
  //     '9. Promote the Brand and prospect at industry events as assigned.',
  //     '10.Other Duties as assigned.',

  //     '11. Where appropriate, provide guidance to the Solution Architect in the development of solutions.',
  //     '12. Highlight all risks and issues that affect development or deliveries.',
  //     '13. Work across teams to define efficient solutions and implementation strategies to create highly cohesive implementation across products.',
  //     '14. Possibly mentor staff in the software development method; coding and testing techniques Demonstrate interest in improving the company’s technical awareness, depth, and use of technology across the business.',
  //     '15. Participate in the evolution of company level best practices, standards, and policies related to software development.',
  //   ],
  //   skills: [
  //     '1. Strong communication and collaboration skills',
  //     '2. Structured, highly analytical mindset and excellent problem-solving skills',
  //     '3. Collaborative, with strong facilitation and people skills/personal impact',
  //     '4. Highly motivated and work well under pressure',
  //     '5. Willing to work on new technologies and languages outside of their core skillset',
  //     '6. Innovative, with the ability to think outside the box',
  //     '7. Fact-based and result oriented',
  //     '8. An individual who respects the opinion of others; yet can drive a decision through the team',
  //     '9. An individual who understands and respects the agile method',
  //     '10. Must have relevant experience of at least 3 years',
  //   ],
  //   performanceObjectives: null,
  //   advantageIf: null,
  //   salary: null,
  // },
  {
    id: 0,
    header: 'Purchasing Manager',
    subHeader: 'Purchase',
    type: 'Full Time',
    locationHeader: 'Faridabad',
    jobPosted: '21 April 2022',
    shortDescription: [
      'The ideal candidate will be responsible for identifying and fostering a relationship with our suppliers and vendors. You will also oversee the implementation of the supply and production strategies.',
    ],
    keyResponsibilities: [
      '1. Procure parts and materials at negotiated rate.',
      '2. Develop a supply and production plan to ensure timely delivery to our customers.',
      '3. Create and monitor the performance of the purchasing strategy.',
      '4. Oversee and support our purchasing staff.',
    ],
    skills: [
      '1. Strong negotiation skills.',
      '2. 5-7 years of purchasing experience.',
      '3. Strong written and verbal communication skills.',
      '4. After sales spare parts sourcing experience.',
      '5. supply chain.',
      '6. strategic sourcing.',
      '7. vendor sourcing.',
      '8. logistics.',
      '9. material management.',
      '10. vendor development.',
    ],
    performanceObjectives: null,
    advantageIf: null,
    salary: null,
    locationDetails: ['Faridabad'],
  },
  {
    id: 1,
    header: 'After Market Sales Head',
    subHeader: 'Sales',
    type: 'Full Time',
    locationHeader: 'Faridabad',
    jobPosted: '21 April 2022',
    shortDescription: [
      'We are looking for a After Market Sales Head to shape our sales department and scale revenue to the next level. The ideal candidate will be responsible architecting a sales strategy and building out a team of Account Executives and SDRs across enterprise and mid-market sales. The person should be excited by selling into new markets, strategizing next steps, negotiating complex deals and beating the competition in head to head opportunities.',
    ],
    keyResponsibilities: [
      '1. Own all plans and strategies for developing business and achieving the company"s sales goals.',
      '2. Assists in the development of the sales plan.',
      '3. Prepares forecasts and KPI reporting for the sales leaders, CRO, and upper management, for use in organizational planning, financial forecasting, budget setting and strategic planning.',
      '4. Land and expand: build process and funnel for manual top-down reachout, on boarding, activation, and expansion.',
      '5. Evangelize the product and personally help close largest deals.',
      '6. Work collaboratively across teams.',
      '7. Establish the inbound lead requirements needed to meet your sales objectives.',
      '8. Establish and foster partnerships and relationships with key customers both externally and internally.',
    ],
    skills: [
      '1. 8-10 years of relevant sales experience and a track record of exceeding quota.',
      '2. Experience in hard core spare parts distribution Channel Development.',
      '3. Possess extensive knowledge of sales principles and practices, and an ability to coach others on them.',
      '4. Strong analytical and quantitative skills; ability to use hard data and metrics to back up assumptions, recommendations, and drive actions.',
      '5. Proven ability to influence cross-functional teams.',
      '6. Strength in problem solving, issue-resolution, ability to work in a deadline-driven work environment, attention to detail, and ability to multitask.',
      '7. Strong leadership and team building skills.',
    ],
    performanceObjectives: null,
    advantageIf: null,
    salary: null,
    locationDetails: ['Faridabad'],
  },
  {
    id: 2,
    header: 'Tele Caller',
    subHeader: 'Sales',
    type: 'Full Time',
    locationHeader: 'Faridabad',
    jobPosted: '21 April 2022',
    shortDescription: [
      'We are interested in hiring a dedicated and hardworking individual as a Tele caller to join our Sales Department.Your main goal is to boost our sales by reaching out to the existing customers as well as potential customers. As a Tele caller, you are responsible for handling sales over the phone entirely. You are also responsible for solving questions in regard to the product or service provided by the company.',
    ],
    keyResponsibilities: [
      '1. Answering phones and explaining the product and services offered by the company.',
      '2. Contacting existing customers as well as prospective customers using scripts.',
      '3. Making recordings of all the sales phone calls and sales deals.',
      '4. Taking and processing product orders in a professional manner.',
      '5. Maintaining the database of the customers on a regular basis.',
      '6. Suggesting solutions based on customer’s needs and requirements.',
    ],
    skills: [
      '1. Any Graduation and Diploma.',
      '2. Work experience as a Tele caller, Telemarketer, or a similar role in the Sales Department.',
      '3. Professional certification sales and marketing will be an advantage..',
      '4. Great interpersonal skills.',
      '5. Exceptional oral and written communication skills.',
      '6. Strong organizational skills.',
      '7. Ability to work in a team or individually as and when required.',
      '8. Ability to manage and handle multiple tasks.',
      '9. Outstanding problem-solving skills.',
      '10. Hard-working individual.',
      '11. Good time management abilities.',
      '12. Strong decision-making skills.',
    ],
    performanceObjectives: null,
    advantageIf: null,
    salary: null,
    locationDetails: ['Faridabad - Number of vacancies: 10'],
  },
  {
    id: 3,
    header: 'Sales and Marketing Executive',
    subHeader: 'Sales',
    type: 'Full Time',
    locationHeader: 'NCR , Bihar , Jammu , Kashmir , West , Bengal , MP , Maharashtra',
    jobPosted: '21 April 2022',
    shortDescription: [
      'We are looking to hire an experienced sales and marketing executive to help drive company sales. In this position, you will be involved in developing marketing strategies, implementing marketing plans, developing sales strategies, maintaining customer relations, and creating sales reports.',
    ],
    keyResponsibilities: [
      '1. Responsible for increase spare part sales.',
      '2. Franchise Business Development.',
      '3. Day by day maintaining sales and spares data of defined areas.',
      '4. Retail marketing to required customer to meet targets.',
      '5. Co-ordination about Regular issues of franchise.',
      '6. Maintaining client relations.',
      '7. Tracking sales data to ensure the company meets sales quotas.',
    ],
    skills: [
      '1. Knowledge of modern marketing techniques.',
      '2. Understanding of commercial trends and marketing strategies.',
      '3. Any Graduation.',
      '4. 0-3 Year Experience.',
    ],
    performanceObjectives: null,
    advantageIf: null,
    salary: null,
    locationDetails: [
      'NCR - Number of vacancies: 3',
      'Bihar - Number of vacancies: 3',
      'Jammu & Kashmir - Number of vacancies: 1',
      'West & Bengal - Number of vacancies: 1',
      'MP - Number of vacancies: 1',
      'Maharashtra - Number of vacancies: 1',
    ],
  },
  // {
  //   id: 4,
  //   header: 'Purchase Assistant Manager',
  //   subHeader: 'Purchase',
  //   type: 'Full Time',
  //   locationHeader: 'Allahabad ,  Azamgarh ,  Gorakhpur ,  Jaunpur ,  Lucknow , Varanasi',
  //   jobPosted: '21 April 2022',
  //   shortDescription: [
  //     'As a Sales Executive, you will be loaded with passion, dedication, hard-working, having good market analyzing skills, sales expertise and must be having excellent communication skills.',
  //   ],
  //   keyResponsibilities: [
  //     '1. Should be aware of supplier development &amp; process.',
  //     '2. Should be able to carry out suppliers negotiation parts development &amp;packaging.',
  //     '3. Proffered from two- wheeler`s supplier knowledge.',
  //     '4. Able to create RFO/ P.O. &amp; Quote and delivery of material.',
  //     '5. Should be able to manage the complete procurement to pay cycle.',
  //     '6. Should be aware of government applicable taxes and documentation.',
  //     '7. Desired candidate will lead the complete supply chain &amp; vendor development activity both.',
  //     '8. Two wheeler all commodity knowledge like (Plastic / Electrical / Filter oil etc).',
  //   ],
  //   skills: [
  //     'Educated to Bachelor Degree',
  //     'Looking for candidate with experience more than 8 years.',
  //     'B.E. , Diploma in mechanical/ Automobile Candidate should have good communication &amp; project co-ordination skills.',
  //     'Microsoft Office and CRM software – ability at the intermediate level',
  //     'They must be good with business and material management .( Preferred from two wheeler industry)',
  //     'They must have Efficient knowledge about Goods available in market.',
  //     'Candidate Must be familiar with ERP/SAP.',
  //     'Excellent oral, written and presentation skills',
  //   ],
  //   performanceObjectives: null,
  //   salary: null,
  //   advantageIf: null,
  //   locationDetails: ['Allahabad', 'Azamgarh', 'Gorakhpur', 'Jaunpur', 'Lucknow', 'Varanasi'],
  // },
  {
    id: 4,
    header: 'Front-End Developer',
    subHeader: 'IT',
    type: 'Full Time',
    locationHeader: 'Faridabad',
    jobPosted: '21 April 2022',
    shortDescription: [
      'As a front-end developer,your responsibilities will include translation of the UI/UX design wireframes to actual code that will produce visual elements of the application. You will work with the UI/UX designer and bridge the gap between graphical design and technical implementation, taking an active role on both sides and defining how the application looks as well as how it works',
    ],
    keyResponsibilities: [
      '1. Reviewing application requirements and interface designs.',
      '2. Identifying web-based user interactions.',
      '3. Developing and implementing highly responsive user interface components using react concepts.',
      '4. Writing application interface codes using JavaScript following react.js workflows.',
      '5. Troubleshooting interface software and debugging application codes.',
      '6. Developing and implementing front-end architecture to support user interface concepts.',
      '7. Monitoring and improving front-end performance.',
      '8. Documenting application changes and developing updates.',
    ],
    skills: [
      '1. Bachelor’s degree in computer science, information technology, or a similar field.',
      '2. Previous experience working as a react.js developer.',
      '3. In-depth knowledge of JavaScript, CSS, HTML, and front-end languages.',
      '4. Knowledge of REACT tools including React.js, Webpack, Redux React Styled Component knowledge also required.',
      '5. GIT knowledge is mandatory.',
      '6. Type Script is also require.',
      '7. Experience with user interface design.',
      '8. Knowledge of performance testing frameworks including Mocha and Jest.',
      '9. Experience with browser-based debugging and performance testing software.',
      '10. Excellent troubleshooting skills.',
      '11. Good project management skills.',
      '12. Experience- 1-2 Year.',
    ],
    performanceObjectives: null,
    advantageIf: null,
    salary: null,
    locationDetails: ['Faridabad'],
  },
  // {
  //   id: 6,
  //   header: 'Full Stack Developer',
  //   subHeader: 'IT',
  //   type: 'Full Time',
  //   locationHeader: 'Faridabad',
  //   jobPosted: '21 April 2022',
  //   shortDescription: [
  //     'As a Full Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility.If you’re also familiar with Agile methodologies.',
  //   ],
  //   keyResponsibilities: [
  //     '1. Developing front end website architecture',
  //     '2. Designing user interactions on web pages.',
  //     '3. Developing back end website applications',
  //     '4. Creating servers and databases for functionality',
  //     '5. Ensuring cross-platform optimization for mobile phones Ensuring responsiveness of applications',
  //     '6. Working alongside graphic designers for web design features',
  //     '7. Seeing through a project from conception to finished product.',
  //     '8. Designing and developing APIs',
  //     '9. Meeting both technical and consumer needs.',
  //   ],
  //   skills: [
  //     'Degree in Computer Science.',
  //     '2 to 4 years of experience in ReactJS and Javascript',
  //     'Strong organizational and project management skills.',
  //     'Proficiency with fundamental front-end languages such as react.js, redux, HTML, CSS, and JavaScript',
  //     'Familiarity with JavaScript frameworks such as React',
  //     'Proficiency with server-side languages such as express.js, node.js',
  //     'Proficiency in REST API',
  //     'Proficiency in code version tools, such as Git',
  //     'Knowledge of data modeling and sequelizer',
  //     'Knowledge of AWS for server management and deployment',
  //     'Familiarity with database technology such as MySQL',
  //     'Good problem-solving skills.',
  //     'KEY SKILLS: Node.js,Express.js, React.js, Redux, AWS, MySQL, JavaScript, HTML, RESTful APIs.',
  //   ],
  //   performanceObjectives: null,
  //   advantageIf: null,
  //   salary: null,
  //   locationDetails: ['Faridabad'],
  // },
  {
    id: 5,
    header: 'Back-End Developer',
    subHeader: 'IT',
    type: 'Full Time',
    locationHeader: 'Faridabad',
    jobPosted: '21 April 2022',
    shortDescription: [
      'Smart Garage is looking for a backend engineer to build an exceptional web application with a focus on the server side. You will be working remotely and may be requested to work from the office (Faridabad).',
    ],
    keyResponsibilities: [
      '1. Build new features and directly impact the future of our product.',
      '2. Work on cutting-edge technologies.',
      '3. Focus on high-end performance backend services by adopting a micro service architecture.',
      '4. Improve and maintain existing modules.',
      '5. Technology - Node.js, Express, Sequelize, SQL DB, AWS, Type Script, GIT, SQL DB',
    ],
    skills: [
      '1. Must have at least 2 years of experience in a backend role.',
      '2. Experience building a micro service from scratch.',
      '3. Full understanding of the HTTP and server-client interactions and intricacies of database performance and infrastructure compatibilities.',
      '4. Understanding of product and have a passion for building software that provides a great experience.',
      '5. Effective at troubleshooting, debugging, and root causing defects in large scale system.',
      '6. Experience with performance optimization approaches (caching, aggregations, compression, etc).',
      '7. Experience Serving as a backend tech lead on large scale projects.',
      '8. Strong understanding of database optimization and debugging techniques.',
      '9. Develop clean, high-quality code and automated tests to verify its operation.',
      '10.Demonstrated strong analytical and problem-solving skills.',
      '11. Team player, strong communication skills, and empathetic.',
      '12. Degree in Computer Science (not a must; we are always looking for super talented people).',
    ],
    performanceObjectives: null,
    advantageIf: null,
    salary: null,
    locationDetails: ['Faridabad'],
  },
  // {
  //   id: 8,
  //   header: 'Node.js Developer',
  //   subHeader: 'IT',
  //   type: 'Full Time',
  //   locationHeader: 'Faridabad',
  //   jobPosted: '21 April 2022',
  //   shortDescription: [
  //     'As a back-end developer, your primary focus will be the development of all server-side logic, definition and maintenance of the central database, and ensuring high performance and responsiveness to requests from the front-end. You will also be responsible for integrating the front-end elements built by your co-workers into the application.',
  //   ],
  //   keyResponsibilities: [
  //     '1. Developing and maintaining all server-side network components.',
  //     '2. Ensuring optimal performance of the central database and responsiveness to front-end requests.',
  //     '3. Collaborating with front-end developers on the integration of elements.',
  //     '4. Designing customer-facing UI and back-end services for various business processes.',
  //     '5. Developing high-performance applications by writing testable, reusable, and efficient code.',
  //     '6. Implementing effective security protocols, data protection measures, and storage solutions.',
  //     '7. Running diagnostic tests, repairing defects, and providing technical support.',
  //     '8. Documenting Node.js processes, including database schemas, as well as preparing reports.',
  //     '9. Recommending and implementing improvements to processes and technologies.',
  //     '10. Keeping informed of advancements in the field of Node.js development.',
  //   ],
  //   skills: [
  //     'At least two years&#39; experience as a Node.js developer.',
  //     'Bachelor&#39;s degree in computer science, information science, or similar.',
  //     'Extensive knowledge of JavaScript, web stacks, libraries, and frameworks.',
  //     'Knowledge of Back-end technologies such as Node.js and Express.js.',
  //     'Superb interpersonal, communication, and collaboration skills.',
  //     'Exceptional analytical and problem-solving aptitude.',
  //     'Great organizational and time management skills.',
  //   ],
  //   performanceObjectives: null,
  //   salary: null,
  //   advantageIf: null,
  //   locationDetails: ['Faridabad'],
  // },
  {
    id: 6,
    header: 'Graphic Designer',
    subHeader: 'IT',
    type: 'Full Time',
    locationHeader: 'Faridabad',
    jobPosted: '21 April 2022',
    shortDescription: [
      'We are looking for a graphic designer who able to design Logos, Brochures, Flyers and other graphics, knowledge of Graphic Designing tools like Adobe Photoshop, Corel Draw, Adobe InDesign, Adobe illustrator, Knowledge of Graphic Designing and its tools.',
    ],
    keyResponsibilities: [
      '1. Collaborate with the team to ensure consistency of designs across various media outlets.',
      '2. Create compelling and effective logos, designs, print, and digital media.',
      '3. Maintain awareness of current industry and technology standards, social media, competitive landscape, and market trends.',
      '4. Conceptualize visuals based on requirements.',
      '5. Study design briefs and determine requirements.',
      '6. Prepare rough drafts and present ideas.',
      '7. Develop illustrations, logos, and other designs using software or by hand.',
      '8. Ensure final graphics and layouts are visually appealing and on-brand.',
      '9. Work with a wide range of media and use graphic design.',
      '10. Think creatively and develop new design concepts, graphics, and Design Digital Campaign.',
    ],
    skills: [
      '1. Bachelor’s degree in Graphic Design or related field.',
      '2. 1-3 years of experience in graphic design.',
      '3. Proficient in Adobe Creative Suite and Corel.',
      '4. Ability to multitask, communicate and present.',
      '5. Strong communication, conceptual thinking, typography skills, and design skills.',
    ],
    performanceObjectives: null,
    salary: '15k - 20k',
    advantageIf: null,
    locationDetails: ['Faridabad'],
  },
  {
    id: 7,
    header: 'UI/UX designer',
    subHeader: 'IT',
    type: 'Full Time',
    locationHeader: 'Faridabad',
    jobPosted: '21 April 2022',
    shortDescription: [
      'As a UI / UX designer, you will be working closely with the founders and the engineering time to deliver top quality user experience. This is a great opportunity and play a strategic role in shaping our user experience.',
    ],
    keyResponsibilities: [
      '1. Execute projects from a UX perspective.',
      '2. Identifying design problems and devising elegant solutions.',
      '3. Building prototypes to validate and test the designs.',
      '4. Presenting ideas, concepts and design solutions to various stakeholders.',
      '5. Defining functionality, navigation, interaction models and visual design.',
      '6. Create UX deliverables like wireframes, user journeys, flows.',
      '7. Work closely with teams to ensure projects are delivered as per specifications.',
      '8. Research ongoing technology and trends.',
    ],
    skills: [
      '1. 1-2 years of work experience in designing great web and mobile applications.',
      '2. Knowledge of Figma & Adobe Photoshop.',
      '3. Knowledge of XD tool.',
      '4. Candidates with good online portfolio will be given priority.',
      '5. You possess a Degree in Design or related field from a top tier institute.',
      '6. You possess excellent communication and interpersonal skills and can articulate your ideas to different stakeholders.',
      '7. Ability to understand the business problem, identify the key challenges, formalize the problem, and prototype solutions',
      '5. Consistent track record of documenting, synthesizing, and communicating results.',
      '5. Must be self-motivated, flexible, collaborative, with an eagerness to learn.',
    ],
    performanceObjectives: null,
    salary: null,
    advantageIf: null,
    locationDetails: ['Faridabad -  Number of vacancies: 3'],
  },
  {
    id: 8,
    header: 'Testing Engineer',
    subHeader: 'IT',
    type: 'Full Time',
    locationHeader: 'Faridabad',
    jobPosted: '21 April 2022',
    shortDescription: [
      'As an experienced software technician / Software Tester, you will be responsible for developing automated tests and performing manual tests, participate in manual test execution, monitoring automated tests, writing scripting tools for automation.',
    ],
    keyResponsibilities: [
      '1. Write scripting tools for automation.',
      '2. Develop automated and manual tests.',
      '3. Executing manual tests and maintaining test infrastructure.',
      '4. Reporting and debugging any issues as and when found.',
      '5. Maintain documentation of test operations and report results.',
      '6. Mentoring and providing technical guidance to junior/entry technicians.',
    ],
    skills: [
      '1. Computer Science or related field with 6 Month to 1 year of professional experience preferably in test development.',
      '2. Thorough understanding of testing concepts and use of automated test tools.',
      '3. Experience in problem solving and good programming and debugging skills.',
    ],
    performanceObjectives: [
      '1. Working closely with development engineers to understand V&V requirements, funnel in the requirements and facilitate smooth functioning of the team.',
      '2. Problem-solving, effectively diagnosing technical issues and proposing reasonable solutions',
      '3. Anticipating problems and having multiple perspectives of a system.',
      '4. Communicating across global locations effectively and efficiently.',
      '5. Taking initiative, being a self-starter, and working independently.',
      '6. Quickly learning applicable technology, systems, and products.',
      '7. Having attention to detail.',
      '8. Taking ownership of goals and project schedules.',
    ],
    advantageIf: null,
    salary: null,
    locationDetails: ['Faridabad'],
  },
]
