export const inspectionCheckList = [
    { label: 'Compression', id: '1',response:'' },
    { label: 'RPM using tacometer', id: '2',response:'' },
    { label: 'Washing', id: '3',response:'' },
    { label: 'Mobil', id: '4',response:'' },
    { label: 'Mobile Filter', id: '5',response:'' },
    { label: 'Air Filter', id: '6',response:'' },
    { label: 'Petrol Pipe', id: '7',response:'' },
    { label: 'Carburator', id: '8',response:'' },
    { label: 'Fuel Supply', id: '9',response:'' },
    { label: 'Taping Nut', id: '10',response:'' },
    { label: 'Back Wheel Movement', id: '11',response:'' },
    { label: 'Brake Shoe', id: '12',response:'' },
    { label: 'Brake Cam', id: '13',response:'' },
    { label: 'Bearing & Sproket', id: '14',response:'' },
    { label: 'Greesing', id: '15',response:'' },
    { label: 'Chainset', id: '16',response:'' },
    { label: 'Battery Charge', id: '17',response:'' },
    { label: 'Clutch', id: '18',response:'' },
    { label: 'Spark Plug', id: '19',response:'' },
    { label: 'Handle Movement', id: '20',response:'' },
    { label: 'Clutch Wire', id: '21',response:'' },
    { label: 'Race Wire', id: '23',response:'' },
    { label: 'Brake Wire', id: '24',response:'' },
    { label: 'IChoke & Choke Wire', id: '25',response:'' },
    { label: 'Ultimeter', id: '26',response:'' },
    { label: 'Front Wheel', id: '27',response:'' },
    { label: 'Front & Rare Wheel Bearing', id: '28',response:'' },
    { label: 'Front  & Rare Socker', id: '29',response:'' }

  ]
